sudo: required
services:
  - docker

before_install:
  - docker build -t brandoncjw/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run brandoncjw/multi-client-test npm test -- --coverage

after_success:
  - docker build -t brandoncjw/multi-client ./client
  - docker build -t brandoncjw/multi-nginx ./nginx
  - docker build -t brandoncjw/multi-server ./server
  - docker build -t brandoncjw/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push brandoncjw/multi-client
  - docker push brandoncjw/multi-nginx
  - docker push brandoncjw/multi-server
  - docker push brandoncjw/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-068353330993
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY